---
name: "process_synergy_tweet_rule"
description: "If tweet from netwookie, process it."
enabled: true

trigger:
  type: "twitter.matched_tweet"
  parameters: {}

action:
  ref: "synergytweet.process_synergy-tweet"
  parameters:
    tweet_body: "{{ trigger }}"
